version: '3.9'

services:
  sqldb:
    image: 'mysql'
    ports:
      - '3306:3306'
    networks:
      - nest-app
    environment:
      - MYSQL_DATABASES=nestjsgraphql
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_HOST=localhost
      - MYSQL_PORT=33306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=""
      - MYSQL_MY_DATABASE=nestjsgraphql

  nestserver:
    build: .
    ports:
      - '3000:3000'
    networks:
      - nest-app
    image: graphqlnest
    depends_on:
      - sqldb

networks:
  nest-app:
    driver: bridge
