version: '3.9'

services:
  sqldb:
    image: 'mysql'
    ports:
      - '3306:3306'
    networks:
      - nest-app
    environment:
      - MYSQL_ROOT_PASSWORD=""

  nestserver:
    build: .
    ports:
      - '3000:3000'
    networks:
      - nest-app
    image: graphqlnest
    depends_on:
      - sqldb

networks:
  nest-app:
    driver: bridge
